name: myblue-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: rpm-ostree
    install:
      - generic-logos
      - generic-release

    remove:
      - firefox
      - firefox-langpacks
      - gnome-tour
      - gnome-classic-session
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-software

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
      - org.mozilla.firefox
      - io.github.flattool.Warehouse

  - type: gnome-extensions
    install:
      - Rounded Window Corners Reborn
      - AppIndicator and KStatusNotifierItem Support

  - type: script
    scripts:
      - hide-apps.sh
  
  - type: bling
    install:
      - ublue-update
      - dconf-update-service

  - type: brew

  - type: signing